// class STATUS_CODE {
//     "BAD_REQUEST": 400
//     "INTERNAL_SERVER_ERROR": 500
//     "PAGE_NOT_FOUND": 404
// }
export enum STATUS_CODE {
    BAD_REQUEST = 400,
    INTERNAL_SERVER_ERROR = 500,
    PAGE_NOT_FOUND = 404,
}
